services:
  xttsrvc:
    container_name: 'xtts-rvc-ui'
    image: 'ericlacasse/xtts-rvc-ui:main'
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - xttsrvc:/home/xttsrvc/XTTS-RVC-UI
      - ./rvcs:/home/xttsrvc/XTTS-RVC-UI/rvcs
      - ./voices:/home/xttsrvc/XTTS-RVC-UI/voices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
volumes:
  xttsrvc: